name: build and publish

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build
        run: |
          npm ci
          npm run build
      - name: publish to netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: build
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: b3cd7cc2-68be-4467-b3a6-38f1fdfa0cfc
